export const ERROR = 'ERROR'

// USER
export const REGISTER_USER = 'REGISTER_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SET_USER = 'SET_USER'
export const USER_LOGIN_STATUS = 'USER_LOGIN_STATUS'

// PROJECT
export const FETCH_USER_PROJECTS = 'FETCH_USER_PROJECTS'
export const FETCH_PROJECT_DETAILS = 'FETCH_PROJECTS_DETAILS'
export const SET_PROJECT_DETAILS = 'SET_PROJECT_DETAILS'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const LEAVE_PROJECT = 'LEAVE_PROJECT'
export const FETCH_PROJECT_INVITATION = 'FETCH_PROJECT_INVITATION'
export const ACCEPT_PROJECT_INVITATION = 'ACCEPT_PROJECT_INVITATION'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_MODAL_INVITE = 'TOGGLE_MODAL_INVITE'
export const TOGGLE_MEMBERS_DROPDOWN = 'TOGGLE_MEMBER_DROPDOWN'

// TASK

export const FETCH_USER_TASKS = 'FETCH_USER_TASKS'
export const GET_BOARDS = 'GET_BOARDS'
export const CREATE_NEW_TASK = 'CREATE_NEW_TASK'
export const TOGGLE_MODAL_TASK = 'TOGGLE_MODAL_TASK'
export const TOGGLE_DETAIL_MODAL = 'TOGGLE_DETAIL_MODAL'
export const EDIT_TASK_DETAILS = 'EDIT_TASK_DETAILS'
export const SET_TASK_DETAILS = 'SET_TASK_DETAILS'
export const DELETE_TASK = 'DELETE_TASK'
export const UPDATE_STATUS = 'UPDATE_STATUS'
